// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mfkomfsqtkbhkoznxmyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ma29tZnNxdGtiaGtvem54bXl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3NDA0MDcsImV4cCI6MjA1NTMxNjQwN30.sz8A_JgW2D_ArbjJ_bnZqpm7_KlpONQqVZsEFXZd5X0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);